#ifndef LLM_TRANSFORM_EQUIVALENCE_PASSES_H
#define LLM_TRANSFORM_EQUIVALENCE_PASSES_H

#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Pass/Pass.h"

// Pulls in the pass base classes (in namespace `impl`) generated by
// mlir-tblgen from `Passes.td`:
//   * `ArrayDataflowEquivalenceBase<T>`     (EquivalenceVerifier.cpp)
//   * `TagLinalgOpsForEquivalenceBase<T>`   (TagLinalgOps.cpp)
#define GEN_PASS_DECL
#include "Passes.h.inc"

#endif // LLM_TRANSFORM_EQUIVALENCE_PASSES_H
