SHAPES:
  BATCH_SIZES: [128, 256]
  SIZES: [768, 1024, 256, 1536, 2048, 512, 128, 3072]
  HEIGHTS: [14, 28, 56, 7, 112, 15, 120, 150, 130, 240, 224, 228]
  CHANNELS: [32, 256, 128, 192, 512, 64, 96, 48, 288, 240, 384]
  KERNELS: [1, 3, 7]
  DILATIONS: [1]
  STRIDES: [1, 2]

OPERATIONS:
  add: 2
  sub: 0
  max: 0
  mul: 0
  abs: 0
  ceil: 0
  copy: 0
  fill: 0
  transpose: 0
  batch_matmul: 0
  batch_matmul_transpose_a: 0
  batch_matmul_transpose_b: 0
  batch_reduce_matmul: 0
  matmul: 2
  matmul_transpose_a: 0
  matmul_transpose_b: 0
  conv_1d: 0
  conv_1d_ncw_fcw: 0
  conv_1d_nwc_wcf: 0
  conv_2d: 0
  conv_2d_nchw_fchw: 2
  conv_2d_ngchw_fgchw: 0
  conv_2d_nhwc_fhwc: 0
  conv_2d_nhwc_hwcf: 0
  conv_3d: 0
  conv_3d_ncdhw_fcdhw: 0
  depthwise_conv_1d_ncw_cw: 0
  depthwise_conv_1d_nwc_wc: 0
  depthwise_conv_1d_nwc_wcm: 0
  depthwise_conv_2d_nchw_chw: 0
  depthwise_conv_2d_nhwc_hwc: 0
  depthwise_conv_2d_nhwc_hwcm: 0
  depthwise_conv_3d_ncdhw_cdhw: 0
  depthwise_conv_3d_ndhwc_dhwc: 0
  depthwise_conv_3d_ndhwc_dhwcm: 0
  pooling_nchw_max: 2
  pooling_nchw_sum: 0
  pooling_ncw_max: 0
  pooling_ncw_sum: 0
  pooling_ndhwc_max: 0
  pooling_ndhwc_min: 0
  pooling_ndhwc_sum: 0
  pooling_nhwc_max: 0
  pooling_nhwc_min: 0
  pooling_nhwc_sum: 0
  pooling_nwc_max: 0
  pooling_nwc_sum: 0
  relu: 2